databases:
  - name: decorte_photography_app_database
    databaseName: decorte_photography_app_database
    user: asami_takaoka
    region: singapore

services:
  - type: web
    name: decorte_photography_app
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: render_app
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false