name: Run RSpec Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: your_database_name
          POSTGRES_USER: your_username
          POSTGRES_PASSWORD: your_password
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 # 使っているRubyのバージョンに合わせてください

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Set up Database
      run: |
        cp config/database.yml.github config/database.yml
        RAILS_ENV=test bundle exec rake db:create db:schema:load

    - name: Run RSpec
      run: bundle exec rspec
